### ISSUE TITLE
Failed to create channel java.io.IOException: Connection reset by peer

### ISSUE THREAD

**Issue by spland** [jchambers/pushy#1010]
```
Failed to create channel
java.io.IOException: Connection reset by peer
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:?]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[?:?]
	at sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[?:?]
	at sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356) ~[?:?]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1134) ~[netty-buffer-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

-------------------
This error is displayed when I send consecutively, I tried to check for packet conflictss, but it didn't work

**Comment by jchambers** [comment]
> This error is displayed when I send consecutively

I'm not totally sure I understand what you mean. Do you mean that you send one push notification successfully, then try to send another and the second notification fails?

> I tried to check for packet conflicts, but it didn't work

I'm really sorry, but I don't know what you mean by "packet conflicts." Do you mean TCP packet retransmissions?

Let's take a step back, though: does this happen every time you try to send a notification? Can you tell us more about your setup? Are you using a proxy, for example?

**Comment by spland** [comment]
Sorry, I may not have made it clear. In a concurrent environment, the same client is used to send, for example, I sent more than a dozen messages at the same time, and then this problem occurred

**Comment by spland** [comment]
> > This error is displayed when I send consecutively
> 
> I'm not totally sure I understand what you mean. Do you mean that you send one push notification successfully, then try to send another and the second notification fails?
> 
> > I tried to check for packet conflicts, but it didn't work
> 
> I'm really sorry, but I don't know what you mean by "packet conflicts." Do you mean TCP packet retransmissions?
> 
> Let's take a step back, though: does this happen every time you try to send a notification? Can you tell us more about your setup? Are you using a proxy, for example?

Sorry, I may not have made it clear. In a concurrent environment, the same client is used to send, for example, I sent more than a dozen messages at the same time, and then this problem occurred

**Comment by spland** [comment]
Sorry, I may not have made it clear. In a concurrent environment, the same client is used to send, for example, I sent more than a dozen messages at the same time, and then this problem occurred

**Comment by spland** [comment]
> I'm not totally sure I understand what you mean. Do you mean that you send one push notification successfully, then try to send another and the second notification fails?
> 
> > I tried to check for packet conflicts, but it didn't work
> 
> I'm really sorry, but I don't know what you mean by "packet conflicts." Do you mean TCP packet retransmissions?
> 
> Let's take a step back, though: does this happen every time you try to send a notification? Can you tell us more about your setup? Are you using a proxy, for example?

yes, proxy is used

**Comment by spland** [comment]
public static  ApnsClient getApnsClient() throws NoSuchAlgorithmException{
        if (apnsClient == null) {
            byte[] bytes = decodeBase64EncodedString(privateKey);

            final PKCS8EncodedKeySpec keySpec = new PKCS8EncodedKeySpec(bytes);
            final KeyFactory keyFactory = KeyFactory.getInstance("EC");
            ECPrivateKey signingKey;
            try {
                signingKey = (ECPrivateKey)keyFactory.generatePrivate(keySpec);
                ApnsSigningKey signing = new ApnsSigningKey(keyId, teamId, signingKey);
                signing.getEncoded();
                apnsClient = new ApnsClientBuilder().setApnsServer(ApnsClientBuilder.PRODUCTION_APNS_HOST)
                    .setProxyHandlerFactory(new HttpProxyHandlerFactory(new InetSocketAddress(proxyAddress, port)))
                    .setSigningKey(signing).setConcurrentConnections(1)
                    .build();
            } catch (Exception e) {
                LogUtils.error("apns push create exception",null,e);
            }
        }
        return apnsClient;
    }
-------------
This is the client I created, is it created incorrectly ？I created it based on token, not in the way of .p12

**Comment by spland** [comment]
PushNotificationFuture<SimpleApnsPushNotification, PushNotificationResponse<SimpleApnsPushNotification>>
                future = apnsClient.sendNotification(simpleApnsPushNotification);
            future.whenComplete((pushNotificationResponse,cause)->{
                if (pushNotificationResponse != null) {
                    if (pushNotificationResponse.isAccepted()) {
                        LogUtils.info("Push notification accepted by APNs gateway.", request);
                        BuyerMessagePushSchedule.buyerAppleSuccessPushCounter.incrementAndGet();
                    } else {
                        String errorReason = pushNotificationResponse.getRejectionReason().toString();
                        if (errorReason.contains("BadDeviceToken") || errorReason.contains("Unregistered")) {
                            userDeviceService.setInvalidStatus(request.getfUserDeviceId());
                        }
                        BuyerMessagePushSchedule.buyerAppleFailurePushCounter.incrementAndGet();
                        LogUtils.error("push apns error", errorReason, null);
                    }
                    
                } else {
                    LogUtils.error("push apns exception cause",cause.getMessage());
                    
                }
            });
--------
This is how I use

**Comment by spland** [comment]
I found the same problem in issues #829
