### ISSUE TITLE
Connection reset by peer.

### ISSUE THREAD

**Issue by modernwild** [jchambers/pushy#1014]
Hello,
I encountered some problems with the latest version of Pushy(v0.15.2) in my project.
In my application, multiple push certificates was used(both token and TLS authentication), and I create a new connection for each certificate.  But it's strange:
```
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_202]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_202]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_202]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_202]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_202]
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:259) ~[netty-buffer-4.1.85.Final.jar:4.1.85.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.85.Final.jar:4.1.85.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
```

The above exception occurred occasionally, and I observed that it always happened when connecting the server with token-based authentication. This error seems to be that Apple's server actively disconnects the connection. I tried to reduce the version of pushy to v0.15.1. I have observed for a few days, so far there is no error. 

Is this problem related to the conflict of netty version?

**Comment by jchambers** [comment]
This _sounds_ to me a lot like it's an upstream issue and is not something within Pushy's control.

> Is this problem related to the conflict of netty version?

That seems very unlikely, but I acknowledge that updating to Netty 4.1.85 is the only seemingly-relevant change between 0.15.1 and 0.15.2.

I recognize that it's been some time since you reported this issue (and I apologize for the delay). Does the problem persist if you switch back to 0.15.2 at this point?

**Comment by modernwild** [comment]
I'm sorry for the conclusion I observed earlier. I deployed the application with 0.15.1, and this problem still occurs (the frequency is very low, only once or twice in a few days). I guess the problem is caused by some other unknown network issue.

I don't switch back to 0.15.2 to test again and I consider continuing to use 0.15.1 in the future. 

Thanks for your work.

**Comment by jchambers** [comment]
Okay; thanks for following up! I agree that this sounds like some poor network connectivity that's beyond our control, and so I'll close this issue for now. If you discover something later that suggests that this _is_ within Pushy's control, please leave a comment and I'll happily reopen the issue!

Also, as a matter of curiosity, where (roughly) is the server that's having this problem? There are some parts of the world (especially China) with lots of users and no APNs servers, and that often contributes to odd network behavior.
