### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: Server chose TLSv1, but that protocol version is not enabled or not supported by the client.

### ISSUE THREAD

**Issue by kkrgwbj** [jchambers/pushy#1019]
pushy version =  0.150

javax.net.ssl.SSLHandshakeException: Server chose TLSv1, but that protocol version is not enabled or not supported by the client.

**Comment by jmason** [comment]
It looks like APNs had an outage last night where TLS/SSL connections could not be negotiated -- we got plenty of those errors, and a few of these too:

```
SSL handshake failed with unexpected error
javax.net.ssl.SSLException: Server selected improper ciphersuite TLS_ECDH_anon_WITH_NULL_SHA
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:219)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:306)
        at sun.security.ssl.ClientHandshaker.serverHello(ClientHandshaker.java:547)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:211)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:750)
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
        at java.io.OutputStream.write(OutputStream.java:75)
```

**Comment by jmason** [comment]
The outage spanned from about 20:40 UTC, then was resolved by 00:30 UTC.

**Comment by kkrgwbj** [comment]
I tried to introduce 
```
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-tcnative-boringssl-static</artifactId>
    <version>2.0.54.Final</version>
    <scope>runtime</scope>
</dependency>

 , but I encountered the same problem, 

```
SSL handshake failed with unexpected error
javax.net.ssl.SSLException: Server selected improper ciphersuite TLS_ECDH_anon_WITH_NULL_SHA
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:219)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:306)
        at sun.security.ssl.ClientHandshaker.serverHello(ClientHandshaker.java:547)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:211)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:750)
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
        at java.io.OutputStream.write(OutputStream.java:75)



but the same code, I am normal in the Windows environment, and I report this error after deploying to a Linux server.

**Comment by kkrgwbj** [comment]
@jchambers would you can help me

**Comment by jchambers** [comment]
@kkrgwbj It sounds like we're trying to cover a few distinct issues here.

The first issue sounds like it was caused by an upstream outage—thanks, @jmason, for calling that out (and it's good to hear from you!).

I'm not sure what's going on in the second case, but it sounds like this is more of a general request for technical support than it is a specific bug report. With that in mind, I'm going to move this to a "discussion" rather than an "issue."
