### ISSUE TITLE
Stream closed before write could take place

### ISSUE THREAD

**Issue by kkrgwbj** [jchambers/pushy#1023]
version :0.15.2

```
io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:173) ~[netty-codec-http2-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.cancel(DefaultHttp2RemoteFlowController.java:481) [netty-codec-http2-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$1.onStreamClosed(DefaultHttp2RemoteFlowController.java:105) [netty-codec-http2-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:357) [netty-codec-http2-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.removeFromActiveStreams(DefaultHttp2Connection.java:1007) [netty-codec-http2-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.deactivate(DefaultHttp2Connection.java:963) [netty-codec-http2-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:515) [netty-codec-http2-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.handler.codec.http2.DefaultHttp2Connection.close(DefaultHttp2Connection.java:153) [netty-codec-http2-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler$BaseDecoder.channelInactive(Http2ConnectionHandler.java:217) [netty-codec-http2-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.channelInactive(Http2ConnectionHandler.java:432) [netty-codec-http2-4.1.85.Final.jar!/:4.1.85.Final]
	at com.eatthepath.pushy.apns.ApnsClientHandler.channelInactive(ApnsClientHandler.java:514) [pushy-0.15.2.jar!/:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305) [netty-transport-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) [netty-transport-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) [netty-transport-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) [netty-transport-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) [netty-handler-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) [netty-transport-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) [netty-transport-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) [netty-transport-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:411) [netty-codec-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376) [netty-codec-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1075) [netty-handler-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305) [netty-transport-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) [netty-transport-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) [netty-transport-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) [netty-transport-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301) [netty-transport-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) [netty-transport-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) [netty-transport-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813) [netty-transport-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566) [netty-transport-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.85.Final.jar!/:4.1.85.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.85.Final.jar!/:4.1.85.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by kkrgwbj** [comment]
22.2.2.1

```
I looked at the error log of the service and found nothing abnormal

**Comment by jchambers** [comment]
I'm afraid you're going to need to provide more information. How often does this happen? Every time you try to send a notification? Can you tell us more about how and where you're using Pushy?

**Comment by kkrgwbj** [comment]
0.15.2 verion

```
Not every time, a probability event. I have discovered a new issue that may have a performance impact. Each push thread is a single thread. How can I enable support for multithreading?


code sample

![image](https://user-images.githubusercontent.com/6836934/235389937-687432a2-ea63-43d8-803a-e9c4d9fd8988.png)

**Comment by kkrgwbj** [comment]
@jchambers can you help me

**Comment by jchambers** [comment]
It sounds like you're just dealing with bad network conditions. It looks like you might be in China; please note that there are no APNs servers in China, and users in China routinely report connectivity problems. This is, sadly, beyond Pushy's control.

Please see https://github.com/jchambers/pushy/wiki/Best-practices#threads-concurrent-connections-and-performance for more information about threading.

Because there doesn't appear to be any action we can take to solve your problem from this end, I'm going to close this issue for now. If you need general technical assistance, please [open a new discussion](https://github.com/jchambers/pushy/discussions/new/choose).
