### ISSUE TITLE
ApnsChannelPool java.io.IOException "Failed to create channel - Connection reset by peer"

### ISSUE THREAD

**Issue by sohabotros** [jchambers/pushy#1038]
Hello,
I am gettig the following warning and am not able to send notifications:

"com.eatthepath.pushy.apns.ApnsChannelPool","message":"Failed to create channel","thrown":{"commonElementCount":0,"localizedMessage":"Connection reset by peer","message":"Connection reset by peer","name":"java.io.IOException","

Here is the full log entry with the stack trace:

{"instant":{"epochSecond":1696446836,"nanoOfSecond":205272000},"thread":"nioEventLoopGroup-2-1","level":"WARN","loggerName":"com.eatthepath.pushy.apns.ApnsChannelPool","message":"Failed to create channel","thrown":{"commonElementCount":0,"localizedMessage":"Connection reset by peer","message":"Connection reset by peer","name":"java.io.IOException","extendedStackTrace":[{"class":"sun.nio.ch.FileDispatcherImpl","method":"read0","file":"FileDispatcherImpl.java","line":-2,"exact":false,"location":"?","version":"?"},{"class":"sun.nio.ch.SocketDispatcher","method":"read","file":"SocketDispatcher.java","line":39,"exact":false,"location":"?","version":"?"},{"class":"sun.nio.ch.IOUtil","method":"readIntoNativeBuffer","file":"IOUtil.java","line":276,"exact":false,"location":"?","version":"?"},{"class":"sun.nio.ch.IOUtil","method":"read","file":"IOUtil.java","line":233,"exact":false,"location":"?","version":"?"},{"class":"sun.nio.ch.IOUtil","method":"read","file":"IOUtil.java","line":223,"exact":false,"location":"?","version":"?"},{"class":"sun.nio.ch.SocketChannelImpl","method":"read","file":"SocketChannelImpl.java","line":356,"exact":false,"location":"?","version":"?"},{"class":"io.netty.buffer.PooledByteBuf","method":"setBytes","file":"PooledByteBuf.java","line":259,"exact":false,"location":"netty-buffer-4.1.84.Final.jar!/","version":"4.1.84.Final"},{"class":"io.netty.buffer.AbstractByteBuf","method":"writeBytes","file":"AbstractByteBuf.java","line":1132,"exact":false,"location":"netty-buffer-4.1.84.Final.jar!/","version":"4.1.84.Final"},{"class":"io.netty.channel.socket.nio.NioSocketChannel","method":"doReadBytes","file":"NioSocketChannel.java","line":357,"exact":false,"location":"netty-transport-4.1.84.Final.jar!/","version":"4.1.84.Final"},{"class":"io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe","method":"read","file":"AbstractNioByteChannel.java","line":151,"exact":true,"location":"netty-transport-4.1.84.Final.jar!/","version":"4.1.84.Final"},{"class":"io.netty.channel.nio.NioEventLoop","method":"processSelectedKey","file":"NioEventLoop.java","line":788,"exact":true,"location":"netty-transport-4.1.84.Final.jar!/","version":"4.1.84.Final"},{"class":"io.netty.channel.nio.NioEventLoop","method":"processSelectedKeysOptimized","file":"NioEventLoop.java","line":724,"exact":true,"location":"netty-transport-4.1.84.Final.jar!/","version":"4.1.84.Final"},{"class":"io.netty.channel.nio.NioEventLoop","method":"processSelectedKeys","file":"NioEventLoop.java","line":650,"exact":true,"location":"netty-transport-4.1.84.Final.jar!/","version":"4.1.84.Final"},{"class":"io.netty.channel.nio.NioEventLoop","method":"run","file":"NioEventLoop.java","line":562,"exact":true,"location":"netty-transport-4.1.84.Final.jar!/","version":"4.1.84.Final"},{"class":"io.netty.util.concurrent.SingleThreadEventExecutor$4","method":"run","file":"SingleThreadEventExecutor.java","line":997,"exact":true,"location":"netty-common-4.1.84.Final.jar!/","version":"4.1.84.Final"},{"class":"io.netty.util.internal.ThreadExecutorMap$2","method":"run","file":"ThreadExecutorMap.java","line":74,"exact":true,"location":"netty-common-4.1.84.Final.jar!/","version":"4.1.84.Final"},{"class":"io.netty.util.concurrent.FastThreadLocalRunnable","method":"run","file":"FastThreadLocalRunnable.java","line":30,"exact":true,"location":"netty-common-4.1.84.Final.jar!/","version":"4.1.84.Final"},{"class":"java.lang.Thread","method":"run","file":"Thread.java","line":829,"exact":true,"location":"?","version":"?"}]},"endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"applicationId":"igtbNotification","applicationType":"JAVA","environment":"DEVELOPMENT","hostIp":"10.199.2.155","hostName":"igtbnotification-dev-81-5v76v","origAppNme":"igtbNotification","serviceName":"igtbnotification"},"threadId":85,"threadPriority":10,"source":{"class":"com.eatthepath.pushy.apns.ApnsChannelPool","method":"lambda$acquireWithinEventExecutor$2","file":"ApnsChannelPool.java","line":160}}

**Comment by sohabotros** [comment]
Here is some cleaner log with stacktrace:

2023-10-05 14:53:54.042  WARN 1 --- [ntLoopGroup-2-1] c.eatthepath.pushy.apns.ApnsChannelPool  : Failed to create channel

java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258) ~[netty-buffer-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[netty-transport-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[netty-transport-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[netty-transport-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-transport-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.74.Final.jar!/:4.1.74.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.74.Final.jar!/:4.1.74.Final]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

**Comment by jchambers** [comment]
Hello. This appears to be a request for general technical support rather than a bug report. Let's move this to a discussion instead of an issue.
