### ISSUE TITLE
Request spending a long time when the certificate expires

### ISSUE THREAD

**Issue by dzy5639313** [jchambers/pushy#1078]
I am using the example code on the repository homepage, and everything is work well when the certificate is valid. But if the certificate has expired, the response time for the first few requests is still normal, as the count of requests increases, the response time for each request becomes longer and longer. What's going on?
There is my code:
```
ApnsPayloadBuilder payloadBuilder = new SimpleApnsPayloadBuilder();
payloadBuilder.setAlertBody(content);
payloadBuilder.setAlertTitle(title);
String payload = payloadBuilder.build();
SimpleApnsPushNotification pushNotification = new SimpleApnsPushNotification(TokenUtil.sanitizeTokenString(operatorAndToken[1]), getTopic(operatorAndToken[0]), payload);
PushNotificationFuture<SimpleApnsPushNotification, PushNotificationResponse<SimpleApnsPushNotification>> sendNotificationFuture = client.sendNotification(pushNotification);
try {
    sendNotificationFuture.whenCompleteAsync((pushNotificationResponse, cause) -> {
        if(pushNotificationResponse != null) {
            if (!pushNotificationResponse.isAccepted()) {
                log.warn("[Apple Send Message] Fail: {}", pushNotificationResponse.getRejectionReason());
                pushNotificationResponse.getTokenInvalidationTimestamp().ifPresent(timestamp -> log.warn("\t…and the token is invalid as of {}", timestamp));
            }
        }else {
            log.warn("[Apple Send Message] Failed, operator: {}, env: {}", operatorAndToken[0], properties.getEnv(), cause);
        }
    });
} catch (Exception ex) {
    log.warn("[Apple Send Message] Error, operator: {}, env: {}", operatorAndToken[0], properties.getEnv(), ex);
}
```
And there is log information：
```
2024-07-18 03:03:36.252  WARN 34682 --- [ntLoopGroup-2-1] c.eatthepath.pushy.apns.ApnsChannelPool  : Failed to create channel

io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_expired
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:477)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_expired
	at sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:335)
	at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:156)
	at sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:588)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:544)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:411)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:390)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:629)
	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:297)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1343)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	... 17 common frames omitted

2024-07-18 03:03:36.254  WARN 34682 --- [onPool-worker-9] c.i.f.user.service.AppleService    : [Apple Send Message] Failed, operator: ***, env: ***

io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_expired
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:477)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_expired
	at sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:335)
	at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:156)
	at sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:588)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:544)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:411)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:390)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:629)
	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:297)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1343)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	... 17 common frames omitted
```
Thank you with your help

**Comment by dzy5639313** [comment]
btw， my pushy version is `0.15.0`

**Comment by jchambers** [comment]
> But if the certificate has expired, the response time for the first few requests is still normal, as the count of requests increases, the response time for each request becomes longer and longer.

How many requests are you sending, and over what period of time? How long is the delay?

> What's going on?

TLS handshakes are expensive. Let's say it takes 100ms to complete a TLS handshake and for the sake of simplicity, let's assume you're using just one concurrent connection. If you try to send 1,000 notifications in a burst, then for each notification:

1. Pushy will look for an existing connection in the connection pool
2. Pushy not find an existing connection, and so will attempt to open a connection
3. The connection attempt will fail with a TLS handshake exception (which you've noted in your logs) after (in our example) 100ms
4. Pushy will remove the failed connection from the connection pool

…and the cycle will repeat, taking 100ms for each notification. The first notification will fail after 100ms. The last notification will fail after 100,000ms (or 1 minute, 40 seconds).

**Comment by dzy5639313** [comment]
> How many requests are you sending, and over what period of time? How long is the delay?
I sent a total of 5 requests within one minute, and the delay for the last request was about 10 seconds(I only send one request at a time)

**Comment by jchambers** [comment]
That's just [exponential backoff](https://github.com/jchambers/pushy/blob/143584b20818a5533f5840bc315fec7080ccdd9d/pushy/src/main/java/com/eatthepath/pushy/apns/ApnsChannelFactory.java#L153-L158), then. Pushy does that on purpose to avoid bombarding APNs servers with failed connection attempts. I think everything is working as intended here.

**Comment by monkeyWie** [comment]
Same problem here, when there are more and more requests, it blocks for hours and eventually crashes our server.

So why not fail fast when the certificate expires?
