### ISSUE TITLE
"Connection closed while SSL/TLS handshake was in progress" Failing after migrating the service in Azure

### ISSUE THREAD

**Issue by Jagkalai10** [jchambers/pushy#1091]
I see similar error after migrating the service in Azure. Firewall opened for outbound to api.push.apple.com, not sure why we don't see any traffic after DNS is resolved. Can you please advise if there any resolution on this?

nioEventLoopGroup-2-1 | c.t.p.a.ApnsChannelFactory | | | Tried to mark promise as "failed," but it was already done. java.nio.channels.ClosedChannelException: null at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1150) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813) at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566) at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.base/java.lang.Thread.run(Thread.java:829) Suppressed: io.netty.handler.ssl.StacklessSSLHandshakeException: Connection closed while SSL/TLS handshake was in progress at io.netty.handler.ssl.SslHandler.channelInactive(Unknown Source)

2024-11-20 16:42:50,640 | DEBUG | nioEventLoopGroup-2-1 | i.n.r.dns.DnsNameResolver | | | [id: 0xae756d38] RECEIVED: UDP [7263: /172.25.0.10:53], DatagramDnsResponse(from: /172.25.0.10:53, to: /0:0:0:0:0:0:0:0:47575, id: 7263, QUERY(0), NoError(0), RD RA) DefaultDnsQuestion(api.push.apple.com. IN A) DefaultDnsRawRecord(api.push.apple.com. 19 IN CNAME 34B) DefaultDnsRawRecord(api-vs.push-apple.com.akadns.net. 19 IN A 4B) DefaultDnsRawRecord(api-vs.push-apple.com.akadns.net. 19 IN A 4B) DefaultDnsRawRecord(api-vs.push-apple.com.akadns.net. 19 IN A 4B) DefaultDnsRawRecord(api-vs.push-apple.com.akadns.net. 19 IN A 4B) DefaultDnsRawRecord(api-vs.push-apple.com.akadns.net. 19 IN A 4B) DefaultDnsRawRecord(api-vs.push-apple.com.akadns.net. 19 IN A 4B) DefaultDnsRawRecord(api-vs.push-apple.com.akadns.net. 19 IN A 4B) DefaultDnsRawRecord(api-vs.push-apple.com.akadns.net. 19 IN A 4B) DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)

**Comment by jchambers** [comment]
Hello. It sounds like you're asking for general technical support rather than reporting a specific bug. Let's move this to a discussion rather than an issue.
