### ISSUE TITLE
Exception while using http proxy

### ISSUE THREAD

**Issue by AloulouAchraf** [jchambers/pushy#764]
Hello,

I'm setting http proxy to connect to apns gateway through this method :  setProxyHandlerFactory(new HttpProxyHandlerFactory(proxy))

When i send a notification i get this error :

java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: failure when writing TLS control frames
	at io.netty.util.concurrent.DefaultPromise.get(DefaultPromise.java:349)

Caused by: javax.net.ssl.SSLException: failure when writing TLS control frames
	at io.netty.handler.ssl.SslHandler.setHandshakeFailureTransportFailure(SslHandler.java:1802)
	at io.netty.handler.ssl.SslHandler.access$600(SslHandler.java:166)
	at io.netty.handler.ssl.SslHandler$2.operationComplete(SslHandler.java:937)
	at io.netty.handler.ssl.SslHandler$2.operationComplete(SslHandler.java:932)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
2020-04-01 16:50:21.127  WARN 18984 --- [ntLoopGroup-5-1] c.e.pushy.apns.ApnsChannelFactory        : Tried to mark promise as "failed," but it was already done.

io.netty.handler.proxy.ProxyConnectException: http, none, /134.209.44.228:80 => api.push.apple.com:443, timeout
	at io.netty.handler.proxy.ProxyHandler$2.run(ProxyHandler.java:199) [netty-handler-proxy-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) [netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.45.Final.jar:4.1.45.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_211]

	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.PendingWriteQueue.safeFail(PendingWriteQueue.java:279)
	at io.netty.channel.PendingWriteQueue.removeAndFailAll(PendingWriteQueue.java:177)
	at io.netty.handler.proxy.ProxyHandler.failPendingWrites(ProxyHandler.java:435)
	at io.netty.handler.proxy.ProxyHandler.failPendingWritesAndClose(ProxyHandler.java:352)
	at io.netty.handler.proxy.ProxyHandler.setConnectFailure(ProxyHandler.java:347)
	at io.netty.handler.proxy.ProxyHandler.access$100(ProxyHandler.java:39)
	at io.netty.handler.proxy.ProxyHandler$2.run(ProxyHandler.java:199)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caused by: io.netty.handler.proxy.ProxyConnectException: http, none, /134.209.44.228:80 => api.push.apple.com:443, timeout
	... 10 more

-----------------------------------

I can successfully send push in the case without proxy.

Can you help me ?

Best regards

**Comment by jchambers** [comment]
Hello! I believe you've already [posted this question to the mailing list](https://groups.google.com/forum/#!forum/pushy-apns), and I do think that's the right home for it. While I'm sorry you haven't received an answer there yet, let's keep the conversation in one place for now.

Thanks for your understanding!

**Comment by AloulouAchraf** [comment]
Hello,
Ok, and  sorry for the inconvenience !

Achraf

Le mer. 1 avr. 2020 à 17:10, Jon Chambers <notifications@github.com> a
écrit :
