### ISSUE TITLE
NPE in ApnsClientHandler

### ISSUE THREAD

**Issue by dbakr** [jchambers/pushy#767]
Version 0.13.11
For some applications, NPE is thrown, I guess when the stream is not found.
Here is the stack trace:

```
java.lang.NullPointerException
	at com.eatthepath.pushy.apns.ApnsClientHandler.onStreamError(ApnsClientHandler.java:475)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.onError(Http2ConnectionHandler.java:634)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders0(DefaultHttp2ConnectionEncoder.java:270)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:167)
	at io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeHeaders(DecoratingHttp2FrameWriter.java:53)
	at io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeHeaders(DecoratingHttp2FrameWriter.java:53)
	at io.netty.handler.codec.http2.StreamBufferingEncoder.writeHeaders(StreamBufferingEncoder.java:153)
	at io.netty.handler.codec.http2.StreamBufferingEncoder.writeHeaders(StreamBufferingEncoder.java:141)
	at com.eatthepath.pushy.apns.ApnsClientHandler.writePushNotification(ApnsClientHandler.java:208)
	at com.eatthepath.pushy.apns.ApnsClientHandler.write(ApnsClientHandler.java:176)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1104)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jchambers** [comment]
Huh. I hate to state the obvious, but that shouldn't happen. Here's the line where things appear to be going wrong:

```java
this.encoder().writeHeaders(context, streamId, headers, 0, false, headersPromise);
```

It can't be `context` that's `null`, since we call `context.newPromise()` on the preceding line. `streamId` is just an `int`, so that can't be it. `headers` can't be `null`, either.

That leaves `headersPromise` and `this.encoder()` as our two suspects. I don't _think_ `headersPromise` can be `null`, but will drill down and confirm that. `this.encoder()` is the main suspect, and I'll have to figure out how and when that can possibly be `null`.

@dbakr How often is this happening? Do these appear in clusters, or are they spread out in time? I'm wondering if this happens when a channel is shutting down, for example.

Thanks for the report!

**Comment by jchambers** [comment]
I should have looked more closely at the stack trace; it's not `this.encoder()`. The stack trace continues into the encoder plumbing, so that's definitely not the issue. Eventually, we get to this `catch` block in `DefaultHttp2ConnectionEncoder`:

```java
{
    // ...
} catch (Throwable t) {
    lifecycleManager.onError(ctx, true, t);
    promise.tryFailure(t);
    return promise;
}
```

The line that's actually throwing in there is:

```
lifecycleManager.onError(ctx, true, t);
```

…and so now I'm wondering if there's a case where `lifecycleManager` can be `null`. I think the same questions apply, though; understanding when and how often this happens will give some clues that will be really helpful in tracking down the problem.

**Comment by dbakr** [comment]
Sorry for the late reply. Our flow is that we are sending notifications to large amount of different apps. So this error we got only for very few of them. I will try to double-check today, but most likely it's happening for those which are misconfigured - most likely, there is a mismatch between the certificate environment and the endpoint.
Will give more info later today.

**Comment by dbakr** [comment]
Hi again. I was desperately trying to reproduce the problem on my local machine. But instead of NullPointer I got a proper error response from the server:
```com.eatthepath.pushy.apns.ApnsClientHandler - Received GOAWAY from APNs server: {"reason":"BadCertificateEnvironment"}```

```java.io.IOException: Stream closed before a reply was received```

I'm using native transports, local machine is MaxOsX (kpoll native), server is linux (epoll native)

**Comment by dbakr** [comment]
Ha! Next time reproduced the NullPointer with both Nio and KQueue transports!
Worked as described above occasionally one time only.

So I have clear steps to reproduce: you have to use a certificate for Test environment (only) on a Prod endpoint.
Let me know if I can debug further for you.


```
java.lang.NullPointerException: null
	at com.eatthepath.pushy.apns.ApnsClientHandler.onStreamError(ApnsClientHandler.java:475) ~[pushy-0.13.11.jar:?]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.onError(Http2ConnectionHandler.java:634) ~[netty-codec-http2-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders0(DefaultHttp2ConnectionEncoder.java:270) ~[netty-codec-http2-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:167) ~[netty-codec-http2-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeHeaders(DecoratingHttp2FrameWriter.java:53) ~[netty-codec-http2-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeHeaders(DecoratingHttp2FrameWriter.java:53) ~[netty-codec-http2-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.handler.codec.http2.StreamBufferingEncoder.writeHeaders(StreamBufferingEncoder.java:153) ~[netty-codec-http2-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.handler.codec.http2.StreamBufferingEncoder.writeHeaders(StreamBufferingEncoder.java:141) ~[netty-codec-http2-4.1.48.Final.jar:4.1.48.Final]
	at com.eatthepath.pushy.apns.ApnsClientHandler.writePushNotification(ApnsClientHandler.java:208) ~[pushy-0.13.11.jar:?]
	at com.eatthepath.pushy.apns.ApnsClientHandler.write(ApnsClientHandler.java:176) ~[pushy-0.13.11.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1104) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) [netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.48.Final.jar:4.1.48.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by jchambers** [comment]
Thank you! This is extremely helpful! I'll investigate and see what I can find.

**Comment by jchambers** [comment]
Wow. I really, really misread that whole stack trace. I had convinced myself that was the cause reported by an exceptionally-completed `Future`, but that's plainly not true. You're absolutely right. The problem is that the stream is null, and we can add a trivial `if (stream != null)` check to solve this problem.

Thanks very much—I'll have a fix up shortly!
