### ISSUE TITLE
java.lang.IllegalStateException: Channel closed before HTTP/2 preface completed.

### ISSUE THREAD

**Issue by pritikelvekar** [jchambers/pushy#777]
Hi ,

I have written a sample java program with pushy and face the following error when sending push notification over wifi connection. If I switch to my mobile hotspot connection to run the program it goes through. Can anyone help with what could be a possible reason for this?

```
[nioEventLoopGroup-2-1] WARN io.netty.resolver.dns.DnsQueryContext - Received a mismatching DNS response: DatagramDnsResponse(from: /192.168.1.1:53, to: /0:0:0:0:0:0:0:0:62202, 49853, QUERY(0), NoError(0), RD RA)
	DefaultDnsQuestion(api.development.push.apple.com. IN A)
	DefaultDnsRawRecord(api.development.push.apple.com. 300 IN CNAME 39B)
	DefaultDnsRawRecord(api.sandbox.push-apple.com.akadns.net. 600 IN A 4B)
	DefaultDnsRawRecord(api.sandbox.push-apple.com.akadns.net. 600 IN A 4B)
	DefaultDnsRawRecord(api.sandbox.push-apple.com.akadns.net. 600 IN A 4B)
	DefaultDnsRawRecord(api.sandbox.push-apple.com.akadns.net. 600 IN A 4B)
	DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Channel closed before HTTP/2 preface completed.
	at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:41)
	at apnsprj.SendNotification.dispatch(SendNotification.java:142)
	at apnsprj.SendNotification.main(SendNotification.java:53)
Caused by: java.lang.IllegalStateException: Channel closed before HTTP/2 preface completed.
	at com.turo.pushy.apns.ApnsChannelFactory$3$2.operationComplete(ApnsChannelFactory.java:218)
	at com.turo.pushy.apns.ApnsChannelFactory$3$2.operationComplete(ApnsChannelFactory.java:212)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1148)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:764)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:740)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:611)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1376)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:624)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:608)
	at io.netty.handler.ssl.SslHandler.closeOutboundAndChannel(SslHandler.java:1586)
	at io.netty.handler.ssl.SslHandler.close(SslHandler.java:710)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:624)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:608)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:465)
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:1003)
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:238)
	at io.netty.bootstrap.Bootstrap$2.operationComplete(Bootstrap.java:229)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:112)
	at io.netty.resolver.InetSocketAddressResolver$1.operationComplete(InetSocketAddressResolver.java:64)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:112)
	at io.netty.resolver.RoundRobinInetAddressResolver$1.operationComplete(RoundRobinInetAddressResolver.java:71)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:176)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:726)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:679)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:335)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:324)
	at io.netty.resolver.dns.DnsResolveContext.access$700(DnsResolveContext.java:62)
	at io.netty.resolver.dns.DnsResolveContext$3.operationComplete(DnsResolveContext.java:375)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:223)
	at io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:42)
	at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:162)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)
[main] INFO com.turo.pushy.apns.ApnsClient - Shutting down.
```

**Comment by jchambers** [comment]
Hello!

This sounds more like a request for general support than it does like a bug report or a feature request. We generally ask people to move these kinds of questions to [the Pushy mailing list](https://groups.google.com/d/forum/pushy-apns) because:

1. The mailing list has a wider audience, and you're more likely to find somebody who has experience with your particular circumstances on the mailing list.
2. Posting your question to the mailing list can help other people who are having the same problem.
3. Because there isn't a bug to fix or a feature to add, we can't reasonably solve your problem by making any kind of engineering change.

That said, it sounds like you're behind a proxy or have some other unusual DNS situation that's causing some difficulty. When you post to the mailing list, please provide any details about your network setup that you think may be relevant.

I emphasize that we'd be happy to help, but let's move this conversation to a different venue. Thanks for your understanding!

**Comment by pritikelvekar** [comment]
Hello,

Thanks for redirecting to the proper channel will take a note of it in
future. I wasn't sure if this was an issue from pushy side or something
else because it suddenly stopped working. Sorry for the inconvenience.

Have posted on the mailing list. As far as network setup is concerned i
don't have any proxy configured and i am using broadband connection.

Thanks and Regards,
Priti Kelvekar
