### ISSUE TITLE
Fail to build Quarkus native image with Java 11

### ISSUE THREAD

**Issue by perbone** [jchambers/pushy#781]
It seems Pushy is incompatible with Quarkus using Java 11. Any suggestion how to solve this?
Thanks!
-- Perbone

```
Error: Unsupported features in 4 methods
Detailed message:
Error: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: Object was reached by 
	reading field io.netty.channel.socket.InternetProtocolFamily.localHost of
		constant io.netty.channel.socket.InternetProtocolFamily@6a2c5d8c reached by 
	scanning method io.netty.resolver.dns.DnsNameResolver.preferredAddressType(DnsNameResolver.java:481)
Call path from entry point to io.netty.resolver.dns.DnsNameResolver.preferredAddressType(ResolvedAddressTypes): 
	at io.netty.resolver.dns.DnsNameResolver.preferredAddressType(DnsNameResolver.java:478)
	at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:436)
	at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:475)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newNameResolver(DnsAddressResolverGroup.java:113)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:93)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:78)
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:68)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:192)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:162)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:139)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:123)
	at tradeadvisor.broker.Broker$1.run(Broker.java:179)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: Object was reached by 
	reading field java.net.InetSocketAddress$InetSocketAddressHolder.addr of
		constant java.net.InetSocketAddress$InetSocketAddressHolder@7f00006a reached by 
	reading field java.net.InetSocketAddress.holder of
		constant java.net.InetSocketAddress@7f00006a reached by 
	reading field io.netty.resolver.dns.SingletonDnsServerAddresses.address of
		constant io.netty.resolver.dns.SingletonDnsServerAddresses@79ba6a9f reached by 
	scanning method io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.nameServerAddressStream(DefaultDnsServerAddressStreamProvider.java:117)
Call path from entry point to io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.nameServerAddressStream(String): 
	at io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.nameServerAddressStream(DefaultDnsServerAddressStreamProvider.java:117)
	at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached0(DnsNameResolver.java:1059)
	at io.netty.resolver.dns.DnsNameResolver.access$600(DnsNameResolver.java:91)
	at io.netty.resolver.dns.DnsNameResolver$6.run(DnsNameResolver.java:1044)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:144)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:89)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:143)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: 
	at parsing io.netty.resolver.dns.DnsNameResolver.resolveHostsFileEntry(DnsNameResolver.java:656)
Call path from entry point to io.netty.resolver.dns.DnsNameResolver.resolveHostsFileEntry(String): 
	at io.netty.resolver.dns.DnsNameResolver.resolveHostsFileEntry(DnsNameResolver.java:648)
	at io.netty.resolver.dns.DnsNameResolver.doResolveAll(DnsNameResolver.java:983)
	at io.netty.resolver.dns.DnsNameResolver.doResolveAll(DnsNameResolver.java:958)
	at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:81)
	at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:96)
	at com.oracle.svm.reflect.InflightNameResolver_resolve_83c4421189a07f3b0e2b4decf5b58356cabb2642_114.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:122)
	at com.sun.proxy.$Proxy319.hashCode(Unknown Source)
	at java.util.HashMap.hash(HashMap.java:339)
	at java.util.HashMap.get(HashMap.java:552)
	at com.oracle.svm.jni.access.JNIReflectionDictionary.getLinkage(JNIReflectionDictionary.java:145)
	at com.oracle.svm.jni.functions.JNIFunctions.RegisterNatives(JNIFunctions.java:350)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_RegisterNatives_7728ce15b57af339792ad95c60f247990e0df65e(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet6Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: 
	at parsing io.netty.resolver.dns.DnsQueryContextManager.getOrCreateContextMap(DnsQueryContextManager.java:111)
Call path from entry point to io.netty.resolver.dns.DnsQueryContextManager.getOrCreateContextMap(InetSocketAddress): 
	at io.netty.resolver.dns.DnsQueryContextManager.getOrCreateContextMap(DnsQueryContextManager.java:96)
	at io.netty.resolver.dns.DnsQueryContextManager.add(DnsQueryContextManager.java:42)
	at io.netty.resolver.dns.DnsQueryContext.<init>(DnsQueryContext.java:69)
	at io.netty.resolver.dns.TcpDnsQueryContext.<init>(TcpDnsQueryContext.java:35)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler$1.operationComplete(DnsNameResolver.java:1244)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler$1.operationComplete(DnsNameResolver.java:1226)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.access$300(DefaultPromise.java:35)
	at io.netty.util.concurrent.DefaultPromise$2.run(DefaultPromise.java:531)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:144)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:89)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:143)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

com.oracle.svm.core.util.UserError$UserException: Unsupported features in 4 methods
Detailed message:
Error: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: Object was reached by 
	reading field io.netty.channel.socket.InternetProtocolFamily.localHost of
		constant io.netty.channel.socket.InternetProtocolFamily@6a2c5d8c reached by 
	scanning method io.netty.resolver.dns.DnsNameResolver.preferredAddressType(DnsNameResolver.java:481)
Call path from entry point to io.netty.resolver.dns.DnsNameResolver.preferredAddressType(ResolvedAddressTypes): 
	at io.netty.resolver.dns.DnsNameResolver.preferredAddressType(DnsNameResolver.java:478)
	at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:436)
	at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:475)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newNameResolver(DnsAddressResolverGroup.java:113)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:93)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:78)
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:68)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:192)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:162)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:139)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:123)
	at tradeadvisor.broker.Broker$1.run(Broker.java:179)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: Object was reached by 
	reading field java.net.InetSocketAddress$InetSocketAddressHolder.addr of
		constant java.net.InetSocketAddress$InetSocketAddressHolder@7f00006a reached by 
	reading field java.net.InetSocketAddress.holder of
		constant java.net.InetSocketAddress@7f00006a reached by 
	reading field io.netty.resolver.dns.SingletonDnsServerAddresses.address of
		constant io.netty.resolver.dns.SingletonDnsServerAddresses@79ba6a9f reached by 
	scanning method io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.nameServerAddressStream(DefaultDnsServerAddressStreamProvider.java:117)
Call path from entry point to io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.nameServerAddressStream(String): 
	at io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.nameServerAddressStream(DefaultDnsServerAddressStreamProvider.java:117)
	at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached0(DnsNameResolver.java:1059)
	at io.netty.resolver.dns.DnsNameResolver.access$600(DnsNameResolver.java:91)
	at io.netty.resolver.dns.DnsNameResolver$6.run(DnsNameResolver.java:1044)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:144)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:89)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:143)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: 
	at parsing io.netty.resolver.dns.DnsNameResolver.resolveHostsFileEntry(DnsNameResolver.java:656)
Call path from entry point to io.netty.resolver.dns.DnsNameResolver.resolveHostsFileEntry(String): 
	at io.netty.resolver.dns.DnsNameResolver.resolveHostsFileEntry(DnsNameResolver.java:648)
	at io.netty.resolver.dns.DnsNameResolver.doResolveAll(DnsNameResolver.java:983)
	at io.netty.resolver.dns.DnsNameResolver.doResolveAll(DnsNameResolver.java:958)
	at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:81)
	at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:96)
	at com.oracle.svm.reflect.InflightNameResolver_resolve_83c4421189a07f3b0e2b4decf5b58356cabb2642_114.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:122)
	at com.sun.proxy.$Proxy319.hashCode(Unknown Source)
	at java.util.HashMap.hash(HashMap.java:339)
	at java.util.HashMap.get(HashMap.java:552)
	at com.oracle.svm.jni.access.JNIReflectionDictionary.getLinkage(JNIReflectionDictionary.java:145)
	at com.oracle.svm.jni.functions.JNIFunctions.RegisterNatives(JNIFunctions.java:350)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_RegisterNatives_7728ce15b57af339792ad95c60f247990e0df65e(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet6Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: 
	at parsing io.netty.resolver.dns.DnsQueryContextManager.getOrCreateContextMap(DnsQueryContextManager.java:111)
Call path from entry point to io.netty.resolver.dns.DnsQueryContextManager.getOrCreateContextMap(InetSocketAddress): 
	at io.netty.resolver.dns.DnsQueryContextManager.getOrCreateContextMap(DnsQueryContextManager.java:96)
	at io.netty.resolver.dns.DnsQueryContextManager.add(DnsQueryContextManager.java:42)
	at io.netty.resolver.dns.DnsQueryContext.<init>(DnsQueryContext.java:69)
	at io.netty.resolver.dns.TcpDnsQueryContext.<init>(TcpDnsQueryContext.java:35)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler$1.operationComplete(DnsNameResolver.java:1244)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler$1.operationComplete(DnsNameResolver.java:1226)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.access$300(DefaultPromise.java:35)
	at io.netty.util.concurrent.DefaultPromise$2.run(DefaultPromise.java:531)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:144)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:89)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:143)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

	at com.oracle.svm.core.util.UserError.abort(UserError.java:79)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:221)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:741)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 4 methods
Detailed message:
Error: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: Object was reached by 
	reading field io.netty.channel.socket.InternetProtocolFamily.localHost of
		constant io.netty.channel.socket.InternetProtocolFamily@6a2c5d8c reached by 
	scanning method io.netty.resolver.dns.DnsNameResolver.preferredAddressType(DnsNameResolver.java:481)
Call path from entry point to io.netty.resolver.dns.DnsNameResolver.preferredAddressType(ResolvedAddressTypes): 
	at io.netty.resolver.dns.DnsNameResolver.preferredAddressType(DnsNameResolver.java:478)
	at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:436)
	at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:475)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newNameResolver(DnsAddressResolverGroup.java:113)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:93)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:78)
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:68)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:192)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:162)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:139)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:123)
	at tradeadvisor.broker.Broker$1.run(Broker.java:179)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: Object was reached by 
	reading field java.net.InetSocketAddress$InetSocketAddressHolder.addr of
		constant java.net.InetSocketAddress$InetSocketAddressHolder@7f00006a reached by 
	reading field java.net.InetSocketAddress.holder of
		constant java.net.InetSocketAddress@7f00006a reached by 
	reading field io.netty.resolver.dns.SingletonDnsServerAddresses.address of
		constant io.netty.resolver.dns.SingletonDnsServerAddresses@79ba6a9f reached by 
	scanning method io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.nameServerAddressStream(DefaultDnsServerAddressStreamProvider.java:117)
Call path from entry point to io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.nameServerAddressStream(String): 
	at io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.nameServerAddressStream(DefaultDnsServerAddressStreamProvider.java:117)
	at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached0(DnsNameResolver.java:1059)
	at io.netty.resolver.dns.DnsNameResolver.access$600(DnsNameResolver.java:91)
	at io.netty.resolver.dns.DnsNameResolver$6.run(DnsNameResolver.java:1044)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:144)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:89)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:143)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: 
	at parsing io.netty.resolver.dns.DnsNameResolver.resolveHostsFileEntry(DnsNameResolver.java:656)
Call path from entry point to io.netty.resolver.dns.DnsNameResolver.resolveHostsFileEntry(String): 
	at io.netty.resolver.dns.DnsNameResolver.resolveHostsFileEntry(DnsNameResolver.java:648)
	at io.netty.resolver.dns.DnsNameResolver.doResolveAll(DnsNameResolver.java:983)
	at io.netty.resolver.dns.DnsNameResolver.doResolveAll(DnsNameResolver.java:958)
	at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:81)
	at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:96)
	at com.oracle.svm.reflect.InflightNameResolver_resolve_83c4421189a07f3b0e2b4decf5b58356cabb2642_114.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:122)
	at com.sun.proxy.$Proxy319.hashCode(Unknown Source)
	at java.util.HashMap.hash(HashMap.java:339)
	at java.util.HashMap.get(HashMap.java:552)
	at com.oracle.svm.jni.access.JNIReflectionDictionary.getLinkage(JNIReflectionDictionary.java:145)
	at com.oracle.svm.jni.functions.JNIFunctions.RegisterNatives(JNIFunctions.java:350)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_RegisterNatives_7728ce15b57af339792ad95c60f247990e0df65e(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet6Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: 
	at parsing io.netty.resolver.dns.DnsQueryContextManager.getOrCreateContextMap(DnsQueryContextManager.java:111)
Call path from entry point to io.netty.resolver.dns.DnsQueryContextManager.getOrCreateContextMap(InetSocketAddress): 
	at io.netty.resolver.dns.DnsQueryContextManager.getOrCreateContextMap(DnsQueryContextManager.java:96)
	at io.netty.resolver.dns.DnsQueryContextManager.add(DnsQueryContextManager.java:42)
	at io.netty.resolver.dns.DnsQueryContext.<init>(DnsQueryContext.java:69)
	at io.netty.resolver.dns.TcpDnsQueryContext.<init>(TcpDnsQueryContext.java:35)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler$1.operationComplete(DnsNameResolver.java:1244)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler$1.operationComplete(DnsNameResolver.java:1226)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.access$300(DefaultPromise.java:35)
	at io.netty.util.concurrent.DefaultPromise$2.run(DefaultPromise.java:531)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:144)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:89)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:143)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:738)
	... 8 more
Error: Image build request failed with exit status 1
```

**Comment by jchambers** [comment]
Respectfully, this sounds like it's an issue better addressed with the Netty folks. Would you mind opening an issue upstream instead?

**Comment by jchambers** [comment]
…though I will point out that googling the error message turns up this issue: https://stackoverflow.com/questions/59011565/no-instances-of-are-allowed-in-the-image-heap-as-this-class-should-be-initia

**Comment by perbone** [comment]
Far enough thanks!

**Comment by jchambers** [comment]
…and it looks like there's already an upstream issue for this: https://github.com/netty/netty/issues/9988
