### ISSUE TITLE
HTTP/2 Http2Exception$StreamException: Stream closed before write could take place

### ISSUE THREAD

**Issue by wrglive** [jchambers/pushy#801]
Hello, when I was accessing the 0.14.0 version, I used MQ to push messages, but when the qps is high, the following exception will occur. Is there any solution? I hope to answer when I have time.

```java
  public ApnsClient buildApnsClient(IOSChannelProvider provider) throws IOException {
        EventLoopGroup eventLoopGroup = new NioEventLoopGroup(provider.getThreadsCount());
        String apnsServer = propertiesConfig.isOnlineEnv() ? ApnsClientBuilder.PRODUCTION_APNS_HOST : ApnsClientBuilder.DEVELOPMENT_APNS_HOST;
        String currentPath = Path.getCurrentPath();
        log.info("act=buildApnsClient apnsServer={} CertFile={} ", apnsServer, currentPath + provider.getCertFilePath());
        return new ApnsClientBuilder()
            .setApnsServer(apnsServer)
            .setClientCredentials(new File(currentPath + provider.getCertFilePath()), provider.getCertPassword())
            .setConcurrentConnections(provider.getConcurrentConnections())
            .setEventLoopGroup(eventLoopGroup)
            .build();
    }
```

Exception: 

```
io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place
at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:167) ~[netty-codec-http2-4.1.48.Final.jar:4.1.48.Final]
at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.cancel(DefaultHttp2RemoteFlowController.java:481) ~[netty-codec-http2-4.1.48.Final.jar:4.1.48.Final]
```

**Comment by wrglive** [comment]
Supplementary note:
I created three clients based on three different devices
One of them is 4 threads and 8 connections
The other two are two threads with 4 connections
I am a Chinese developer. Does it have anything to do with the Internet?

**Comment by wrglive** [comment]
This problem has been plagued for a long time. The version has also been upgraded from 0.12 to 0.14
However, high concurrency will still cause messages to accumulate, and only a restart can solve the problem.

I will continue to follow up on this issue in the future, I can provide any information you need,
By the way, can you use client.close() to close and recreate to solve the problem, so that the message in the memory will be lost?

**Comment by liu76874151** [comment]
I have the same problem。I set a maximum of 200 push messages per batch。

io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place
    at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:167)
    at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.cancel(DefaultHttp2RemoteFlowController.java:481)
    at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$1.onStreamClosed(DefaultHttp2RemoteFlowController.java:105)
    at io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:356)
    at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.removeFromActiveStreams(DefaultHttp2Connection.java:1000)
    at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.deactivate(DefaultHttp2Connection.java:956)
    at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:512)
    at io.netty.handler.codec.http2.DefaultHttp2Connection.close(DefaultHttp2Connection.java:152)
    at io.netty.handler.codec.http2.Http2ConnectionHandler$BaseDecoder.channelInactive(Http2ConnectionHandler.java:209)
    at io.netty.handler.codec.http2.Http2ConnectionHandler.channelInactive(Http2ConnectionHandler.java:417)
    at com.eatthepath.pushy.apns.ApnsClientHandler.channelInactive(ApnsClientHandler.java:499)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
    at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
    at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
    at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
    at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1114)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
    at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
    at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:745)

**Comment by jchambers** [comment]
> I am a Chinese developer. Does it have anything to do with the Internet?

That seems likely. Generally speaking, we've found that packet loss to the APNs servers from mainland China is generally very high. I think the next step is to understand if _streams_ are getting handled incorrectly or if _connections_ are closing unexpectedly. There's not much we can do about the latter, unfortunately, but if we can show that it's the former, there may be more to look into.

**Comment by jchambers** [comment]
> The version has also been upgraded from 0.12 to 0.14 However, high concurrency will still cause messages to accumulate, and only a restart can solve the problem.

Also, as a clarification, is the accumulation behavior _new_ in 0.14, or do you just mean that it did not get resolved by upgrading from 0.12 to 0.14?

**Comment by wrglive** [comment]
The problem should have been resolved. When I use whenComplete, sometimes the callback function cannot be successfully executed, which causes the semaphore release to fail, so I use "RateLimiter".

**Comment by wuxuguang** [comment]
@wrglive 用限流来解决apns的回调qps过高吗？那岂不是有一部分回调丢掉了？
