### ISSUE TITLE
Connection reset by peer during initial connection to prod APNS host after app startup.

### ISSUE THREAD

**Issue by mk352** [jchambers/pushy#829]
I'm having intermittent issues when trying to send a notification for the first time with a fresh connection to the APNS prod environment after my app first comes up. When the app starts, there are no connections available yet. When a request is received, I check my JVM cache for an existing ApnsClient. If one does not exist, I build a new client and cache it for reuse. I have implemented  a custom metrics listener and I can see the following Exception printed in the logs:

```
**11/03/2020 18:19:09.530 -0800 ERROR [nioEventLoopGroup-5-1] c.v.e.p.a.ApnsMetricsListener:53  APNS Connection: Status=Failed**
11/03/2020 18:19:09.532 -0800  WARN [nioEventLoopGroup-5-1] c.e.p.a.ApnsChannelPool:160  Failed to create channel
java.io.IOException: **Connection reset by peer**
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_162]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_162]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_162]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_162]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_162]
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133) ~[netty-buffer-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) [netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.51.Final.jar!/:4.1.51.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
**11/03/2020 18:19:09.536 -0800 ERROR [nioEventLoopGroup-5-1] c.v.e.p.a.ApnsMetricsListener:21  APNS Notification: Status=WriteFailure**
```

I have the following in my POM:

Spring Boot 2.3.2

```xml
<dependency>
    <groupId>com.eatthepath</groupId>
    <artifactId>pushy</artifactId>
    <version>0.14.2</version>
</dependency>

<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-tcnative-boringssl-static</artifactId>
    <version>2.0.26.Final</version>
    <scope>runtime</scope>
</dependency>
```

I've implemented a retry loop when this exception is thrown and eventually the connection is successful but ideally this should connect on the first try without any issues.

**Comment by mk352** [comment]
More context:

At our job, we have a staging environment separate from production. Our staging environment is set up to allow APNS clients to connect to the production APNS environment. We have several apps that share the same Auth (P8) key. I'm wondering:

- Is it possible Apple is rejecting too many connections with the same auth key?
- Is it possible Apple is rejecting connections to their prod environment from 2 different sources (different IPs/ranges)?

We're going to review the logic in the application and create a single APNS client per Auth key/environment which will enable us to have less APNS clients.

I enabled TRACE logs but did not see much information other than the 'pings' and 'Received settings from APNs gateway' logs. Is there anything else I can look out for to troubleshoot?

**Comment by mk352** [comment]
@jchambers Can you provide any insight?

**Comment by jchambers** [comment]
Unfortunately, "connection reset by peer" is one of those really annoying problems where the description is technically correct, but not very helpful. All we really know—and all we CAN really know—is that the remote server closed the connection and didn't tell us why.

> I've implemented a retry loop when this exception is thrown and eventually the connection is successful but ideally this should connect on the first try without any issues.

What, exactly, are you retrying when this happens? Are you creating a new `ApnsClient` instance every time?

Also, you pointed out that you're using netty-tcnative-boringssl-static 2.0.26.Final. Please note that's several versions old (you'll probably want 2.0.34.Final if you're using Pushy 0.14.2), and netty-tcnative isn't required to use Pushy. To eliminate some variables, it might be helpful to update to the latest version or to remove it entirely.

> Is there anything else I can look out for to troubleshoot?

You might consider [adding an HTTP/2 frame listener](https://pushy-apns.org/apidocs/0.14/com/eatthepath/pushy/apns/ApnsClientBuilder.html#setFrameLogger(io.netty.handler.codec.http2.Http2FrameLogger)). If the problem is at the connection level, though, that may not tell us much. Still, can't hurt to look.

**Comment by jchambers** [comment]
@mk352 I'm going to close this issue due to inactivity; if you have an opportunity to provide more information, please do so and we'll happily revisit this issue.

**Comment by mkieloch-352** [comment]
@jchambers An update to this. I added a proxy configuration to my clients using this: 
clientBuilder.setProxyHandlerFactory(new HttpProxyHandlerFactory(new InetSocketAddress(proxyUrl, proxyPort), null, null));

and things seemed to start working. What doesn't make sense is that our infra team did open firewalls for the 2 APNS endpoints (prod and sandbox) from our network and for the longest time, that worked fine. Any thoughts on that?
