### ISSUE TITLE
Periodically losing pushes after GOAWAY

### ISSUE THREAD

**Issue by mistahenry** [jchambers/pushy#865]
Hi I'm using pushy 0.14.2 in production. We send around ~50 pushes/second using pushy and have been very happy with it, except for a few instances where we will lose pushes after a GOAWAY with the following error:

```
io.netty.handler.codec.http2.Http2Exception$StreamException: Cannot create stream 6920771 greater than Last-Stream-ID 6920769 from GOAWAY.
        at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:147) ~[netty-codec-http2-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.checkNewStreamAllowed(DefaultHttp2Connection.java:874) ~[netty-codec-http2-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:748) ~[netty-codec-http2-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:668) ~[netty-codec-http2-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders0(DefaultHttp2ConnectionEncoder.java:200) ~[netty-codec-http2-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:166) ~[netty-codec-http2-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeHeaders(DecoratingHttp2FrameWriter.java:53) ~[netty-codec-http2-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeHeaders(DecoratingHttp2FrameWriter.java:53) ~[netty-codec-http2-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.handler.codec.http2.StreamBufferingEncoder.writeHeaders(StreamBufferingEncoder.java:153) ~[netty-codec-http2-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.handler.codec.http2.StreamBufferingEncoder.writeHeaders(StreamBufferingEncoder.java:141) ~[netty-codec-http2-4.1.52.Final.jar!/:4.1.52.Final]
        at com.eatthepath.pushy.apns.ApnsClientHandler.writePushNotification(ApnsClientHandler.java:207) ~[pushy-0.14.2.jar!/:na]
        at com.eatthepath.pushy.apns.ApnsClientHandler.write(ApnsClientHandler.java:175) ~[pushy-0.14.2.jar!/:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294) ~[netty-transport-4.1.52.Final.jar!/:4.1.52.Final]
        at com.eatthepath.pushy.apns.ApnsClient.lambda$sendNotification$1(ApnsClient.java:205) ~[pushy-0.14.2.jar!/:na]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[netty-common-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551) ~[netty-common-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) ~[netty-common-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) ~[netty-common-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604) ~[netty-common-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) ~[netty-common-4.1.52.Final.jar!/:4.1.52.Final]
        at com.eatthepath.pushy.apns.ApnsChannelPool.acquireWithinEventExecutor(ApnsChannelPool.java:174) ~[pushy-0.14.2.jar!/:na]
        at com.eatthepath.pushy.apns.ApnsChannelPool.lambda$acquire$0(ApnsChannelPool.java:126) ~[pushy-0.14.2.jar!/:na]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106) ~[netty-common-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-transport-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.52.Final.jar!/:4.1.52.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.52.Final.jar!/:4.1.52.Final]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

It's seems worth noting that this issue resolved itself exactly 30 seconds after GOAWAY in both instances where this happened for us. During these 30 seconds, all pushes fail to deliver. 

30 seconds on the dot feels very much like a timeout. I did check, and 30 seconds is the TTL for the `api.push.apple.com`. Perhaps it's related?

**Comment by jchambers** [comment]
Can you define what it means to "lose" a push notification a little more precisely? Are the futures failing? Are they not resolving at all (or after a 30-second delay)?

**Comment by mistahenry** [comment]
> Can you define what it means to "lose" a push notification a little more precisely? Are the futures failing?

Sorry if this wasn't clear. The push fails to send, so I schedule it for up to 3 retries with a linear backoff over ~15 seconds. My specific application needs requires as close to "real-time" as possible, so after 15 seconds the push is very late and we discard. Since more than 30 seconds elapsed before the connection healed, hundreds of pushes were discarded after failing 3 retries. 

Below is a reduced example of my code:

```java
sendNotificationFuture.whenComplete((pushNotificationResponse, cause) -> {
  if (pushNotificationResponse != null) {
    // Handle the push notification pushNotificationResponse as before from here.
    if (!pushNotificationResponse.isAccepted()) {
      // attempt a retry
    }
}
```

I'm ending up in the "attempt a retry" block. At exactly 30 seconds after the issue started happening, many of the retries begin succeeding again.

**Comment by jchambers** [comment]
Understood; thanks for the clarification!

**Comment by jchambers** [comment]
With apologies for the delay, it looks like we just need to explicitly close connections when we get a `GOAWAY` frame. I had previously believed that would Just Happen™, but reading through the Netty code, I don't see where that would actually happen.

I'll have a fix up shortly.

**Comment by mistahenry** [comment]
This looks great thanks @jchambers
