### ISSUE TITLE
Support for newer netty (4.1.53)

### ISSUE THREAD

**Issue by lixelu** [jchambers/pushy#892]
I have some dependencies in my project that require netty 4.1.53.
Pushy terminates with this erorr if I enforce this version o netty:

io.netty.channel.StacklessClosedChannelException

**Comment by jchambers** [comment]
As of 381c3959b5f3d248670726d087bb9e6f0dd66071, Pushy uses Netty 4.1.62.

Can you please provide a more complete stack trace or example code so we can better understand the problem?

**Comment by lixelu** [comment]
this reproduces on ubuntu, tomcat container, java 1.8.182. The errors I see are:

2021-Jun-10 12:56:08 PM [nioEventLoopGroup-51-1] WARN   com.eatthepath.pushy.apns.ApnsChannelPool - Failed to create channel
io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(ChannelPromise)(Unknown Source) ~[netty-all-4.1.53.Final.jar!/:4.1.53.Final]

2021-Jun-10 12:56:08 PM [nioEventLoopGroup-51-1] WARN   io.netty.channel.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0x8bd83c44]
java.lang.NoSuchFieldError: SSL_MODE_ENABLE_FALSE_START
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.<init>(ReferenceCountedOpenSslEngine.java:355) ~[netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.newEngine0(ReferenceCountedOpenSslContext.java:409) ~[netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.newHandler(ReferenceCountedOpenSslContext.java:394) ~[netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.handler.ssl.SslContext.newHandler(SslContext.java:999) ~[netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at com.eatthepath.pushy.apns.ApnsChannelFactory$1.initChannel(ApnsChannelFactory.java:105) ~[pushy-0.14.2.jar!/:?]
	at com.eatthepath.pushy.apns.ApnsChannelFactory$1.initChannel(ApnsChannelFactory.java:100) ~[pushy-0.14.2.jar!/:?]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938) ~[netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ~[netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) ~[netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) ~[netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) ~[netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) ~[netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:502) ~[netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:468) ~[netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:87) ~[netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:81) ~[netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86) ~[netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:323) ~[netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:155) ~[netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:116) ~[netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at com.eatthepath.pushy.apns.ApnsChannelFactory.lambda$create$2(ApnsChannelFactory.java:175) ~[pushy-0.14.2.jar!/:?]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) [netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.53.Final.jar!/:4.1.53.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Comment by jchambers** [comment]
Are you using `netty-tcnative`?

**Comment by lixelu** [comment]
yes. I have this in gradle as well
    runtime 'io.netty:netty-tcnative-boringssl-static:2.0.20.Final'

**Comment by lixelu** [comment]
Thank you for your fast responses. I will take this lead and further investigate on my side.

**Comment by lixelu** [comment]
Indeed there was an incompatibility between netty-tcnative-boringssl and netty-all. Thank you for the hint!

**Comment by jchambers** [comment]
Excellent! Glad that resolved things for you.

**Comment by jdschmitt** [comment]
For anyone else who stumbles on this like I did, here is a bit more of what I did to find the right version to fix things on my end.

1. Looked at dependency list in my IDE to see what version of netty I had (4.1.53.Final, in my case)
2. Review the [netty tags here](https://github.com/netty/netty/tags) to see when that version was released. (Oct 13, 2020)
3. Review the [tcnative tags here](https://github.com/netty/netty-tcnative/tags) to see what was the latest version on that date (2.0.34.Final)

Those steps may be obvious but maybe at least having the links here will help speed things up.
