### ISSUE TITLE
Could not initialize class io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider at pushy.apns.ApnsChannelFactory

### ISSUE THREAD

**Issue by ParcellockSB** [jchambers/pushy#933]
First of all, please let me know whether this could be written here, i am not sure, I dont usually write questions. 

Good morning, I am currently using pushy version 0.14.2 and I have been getting this problem in production: 

```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider
	at com.eatthepath.pushy.apns.ApnsChannelFactory.<init>(ApnsChannelFactory.java:87)
	at com.eatthepath.pushy.apns.ApnsClient.<init>(ApnsClient.java:147)
	at com.eatthepath.pushy.apns.ApnsClientBuilder.build(ApnsClientBuilder.java:564)
	at eu.unibox.backend.services.PushNotificationService.sendApplePush(PushNotificationService.java:192)
	at eu.unibox.backend.services.PushNotificationService.sendPush(PushNotificationService.java:162)
	at eu.unibox.backend.services.PushNotificationService.sendToDevice(PushNotificationService.java:133)
	at eu.unibox.backend.services.PushNotificationService.sendToDevices(PushNotificationService.java:128)
	at eu.unibox.backend.services.PushNotificationService.sendTrackAndTraceNotification(PushNotificationService.java:97)
	at sun.reflect.GeneratedMethodAccessor1892.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509)
	at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.delegateInterception(Jsr299BindingsInterceptor.java:79)
	at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.doMethodInterception(Jsr299BindingsInterceptor.java:89)
	at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:102)
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:43)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:40)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
	at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:52)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:54)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:249)
	... 41 more
```

Some devices work, some devices does not work, I can only find this in logs.

This is what I have, and the line *PushNotificationService.java:192* is the build() (last line here in pasted code)

```
  ApnsClient apnsClient = new ApnsClientBuilder()
                    .setApnsServer(ApnsClientBuilder.PRODUCTION_APNS_HOST)
                    .setSigningKey(ApnsSigningKey
                            .loadFromPkcs8File(
                                    new File(configuration.getStringValue(Parameter.XXX)),
                                    configuration.getStringValue(Parameter.XXX),
                                    configuration.getStringValue(Parameter.XXX)))
                    .build();
```

Not really sure what to do or where to ask this, so, thanks in advance for any help

**Comment by sunng87** [comment]
This is caused by different versions of netty on classpath. You might want to checkout your classpath to see if there are different netty versions.

**Comment by ParcellockSB** [comment]
> This is caused by different versions of netty on classpath. You might want to checkout your classpath to see if there are different netty versions.

Thanks @sunng87 , I found this taking a look at gradle dependencies: 

<img width="374" alt="Screenshot 2021-12-17 at 7 36 10 PM" src="https://user-images.githubusercontent.com/41989847/146591979-f10c7694-0449-4630-936c-db6c7ea287a8.png">

so it looks like pushy is using already a different version of netty than the one I have. Not sure whether this is what you mean, but if so, how can I fix it? downgrade the netty import to the one inside pushy? if this is not what you mean, please let me know.

thanks a lot for answering to me :)

**Comment by sunng87** [comment]
You can simply change your netty-all dependency to 4.1.53. I guess you do not depend on any particular features in 4.1.62

**Comment by jchambers** [comment]
It sounds like this is a not a bug and we've identified a solution (thanks, @sunng87, for chiming in!), and so I'm going to close this issue. At the same time, I think this is something other folks may run into in the future, so I'm actually going to close this by way of turning it into a discussion.

Cheers!
