### ISSUE TITLE
How to get all dependent jars to use pushy.jar?

### ISSUE THREAD

**Issue by kinju4374** [jchambers/pushy#955]
Hi,

I am trying to implement new apple push notifications and want to try them first on my local machine with a small java project. I have created a project successfully and have added pushy.jar by downloading from the reference link provided.

Now, after following the instructions and adding code, I didn't get any error in the code but got the following error as below

```
Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/handler/ssl/CipherSuiteFilter
	at applePush.main.main(main.java:21)
Caused by: java.lang.ClassNotFoundException: io.netty.handler.ssl.CipherSuiteFilter
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
```

So, I checked and found that you have provided other reference link but I can't find any jar file's on those links. Could you please guide me through it?

**Comment by jchambers** [comment]
> Could you please guide me through it?

Sorry, but I'm not in a position to provide technical support for other folks' projects.

That said, the reason you're having trouble finding these instructions is that practically everybody uses something like [Maven](https://maven.apache.org/) or [Gradle](https://gradle.org/) to manage dependencies for their project. I recommend that you do so, too.
