### ISSUE TITLE
APNS Connection Issue: Unable to resolve host

### ISSUE THREAD

**Issue by durran-kelly** [jchambers/pushy#996]
Hello,

I'm new to pushy and am using version: **0.15.1**. I'm creating my client in the following way:

```java
apnsClient = new ApnsClientBuilder()
                .setApnsServer(ApnsClientBuilder.DEVELOPMENT_APNS_HOST)
                .setSigningKey(ApnsSigningKey.loadFromPkcs8File(new File("<actualp8Path>"),
                        "<actualTeamId>", "<actualKeyId>"))
                .build();
```

Whenever I send a push notification, I get the following error:

```java
2022-11-27 00:52:48,218 WARN  [com.eat.pus.apn.ApnsChannelPool] (nioEventLoopGroup-2-1) Failed to create channel: java.net.UnknownHostException: Failed to resolve 'api.sandbox.push.apple.com' after 2 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1047)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1000)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:418)
	at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:66)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:467)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
...
Caused by: io.netty.resolver.dns.DnsNameResolverException: [/[2001:4860:4860:0:0:0:0:8844]:53] failed to send a query via UDP (no stack trace available)
Caused by: java.net.NoRouteToHostException: No route to host
	at java.base/sun.nio.ch.DatagramChannelImpl.send0(Native Method)
	at java.base/sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:901)
	at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:863)
	at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:821)
	at io.netty.channel.socket.nio.NioDatagramChannel.doWriteMessage(NioDatagramChannel.java:296)
	at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:143)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
```

Is there a known issue with the version of netty pushy is using? If so, is there any workaround that I can make use of?

Thanks for this awesome library!

**Comment by jchambers** [comment]
It sounds like you're running into the same problem described in #988. In short, it looks like this is an IPv6 issue. Does this problem go away if you run your application with `-Djava.net.preferIPv4Stack=true`?

**Comment by durran-kelly** [comment]
@jchambers, yes that fixed it! Sorry I didn't notice that duplicate issue. Thank you!

**Comment by jchambers** [comment]
No worries; it sounds like this is enough of A Thing that it might be worth adding to the README or FAQ. For reference: what OS are you using? Does it seem like this is a macOS thing specifically?

**Comment by durran-kelly** [comment]
@jchambers Thanks!. Yes, I'm on macOS Ventura 13.0. I'm not sure if it is a macOS thing specifically as I haven't deployed it yet to my dev environment (which is linux). The backend code that utilizes Pushy is ran on Java 17.
